### PR TITLE
Replace test/file-url with npm package

### PR DESCRIPTION
**Pull request by janclarin**
To confirm that the test still works, I ran `./test.sh`. Unsure if file-url should be package.json's dependencies or devDependencies. Thoughts?

### CODE REVIEW

**Comment by irisli** [comment]
I appreciate this to clean up the code. The original intention of checking in file-url was to reduce the number of dependencies. Ideally, all the dependencies are copied and checked into this repo. This is kinda weird, but I think it's slightly more secure.

**Comment by janclarin** [comment]
Oh interesting! I've never thought of that before. Could another solution be to commit the node_modules package and enforce strict package versions in package.json?

It's easier to keep track of package versions through package.json and we keep all of the dependencies in the one default place, which is easily accessible from other files.

**Comment by irisli** [comment]
I wonder if there is a good way to check in node_modules. Have to be careful to not check in any built binaries, and seems like it could cause many problems.

Alternatively, maybe I'm being overconcerned with this dependency thing and there are many other things to spend my time worrying about.

**Comment by janclarin** [comment]
I'm not sure about checking in node_modules either. By not using package.json, you do miss out on GitHub can [security alerts](https://github.com/blog/2470-introducing-security-alerts-on-github) for packages with known vulnerabilities. Although, I'm not sure if that's really important.

Keeping versions may make it easier to identify which packages are causing issues 5 years down the road though! Regardless, I think there needs to be consistency with the packages - either all committed or all in package.json.

Also, I haven't seen any other copy-pasted packages in the repo. Are there any others?

**Comment by irisli** [comment]
I'm already using package.json for a ton of dependencies.

GitHub security alerts are irrelevant because StellarTerm is well insulated. I'm also not worried about the 5 year longevity of this project. I'm mostly concerned about dependencies hijacked by a hacker and malicious code being added.

**Comment by irisli** [comment]
I think one thing you can work on is getting trades to show up in the graph correctly.

Right now, StellarTerm only loads the last 1000 trades that have occurred. Unfortunately, with pairs with lots of trading activity, 1000 trades end up just being the past few hours. Horizon recently added support for "Aggregated trades" where with one api request, it will efficiently return many days of trades.

Also, we don't need candlestick charts for now. But seeing the full history would be super helpful

**Comment by janclarin** [comment]
If this is the only copy-pasted file, wouldn't it make sense to make it consistent with the rest of the project? We can create an issue and revisit the dependencies another time. Otherwise, let's close this pull request.

Cool! Glad to see that functionality. Is there anything else you'd like done? Didn't have time yesterday 😓

**Comment by irisli** [comment]
Yeah, ideally, the rest of the project also becomes copy-pasted to be consistent with that one file.

Theres two things, i'd need:
1. Moving the session stuff into a separate file
2. Asynchronous transaction signing/submission. Right now, when users click to submit a transaction, it's basically synchronous (to the user). Instead, we need a thing where when a transaction is created, a modal opens up on the screen asking the user to confirm sending the transaction. If they confirm, then the transaction is sent. If they cancel, then the modal goes away and it's as if a no-op happened

**Comment by janclarin** [comment]
In that case, I'll close this pull request. Would you mind creating issues for those two things?

Not really sure what "session stuff" means 😞

**Comment by irisli** [comment]
Oh, thats just boring refactoring

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/issues/138

The `Driver` stuff doesn't use any external state machines (like redux or mobx). It's intentional to keep things simpler.

**Comment by irisli** [comment]
https://github.com/irisli/stellarterm/issues/139

^ This too

**Pull request closed without merging**
