### PR TITLE
Add CHRC

### PR DESCRIPTION
**Pull request by jonasess**

### CODE REVIEW

**Comment by jonasess** [comment]
which thing left to add CHRC?

**Comment by charnasol** [comment]
I saw that it now disappeared from the StellarTerm site?

**Comment by irisli** [comment]
The market spread was too wide and the website didn't meet the SSL requirements.

**Comment by charnasol** [comment]
Many people have tokens on your site, our site does have SSL enabled. Is not the point of any coin or token to have normal trading whether high or low? https://CharnaToken.top

**Comment by charnasol** [comment]
You have other stellar tokens listed that are not even active yet you delist over wide trading? I hope our holders can get their tokens out.

**Comment by irisli** [comment]
People can still access their accounts by using another client

**Comment by charnasol** [comment]
The SSL was good enough to list it initially. Than suddenly that changed. SSL doesn’t change overnight. And the spreads were normal for trading. Seems we were only token singled out.

**Comment by irisli** [comment]
Your ssl is still broken.

I just added you back to StellarTerm.

**Comment by irisli** [comment]
I do ask one thing. Please remove StellarTerm from your website.

**Comment by charnasol** [comment]
SSL will be normal tomorrow. Investigating it. Curious any particular reason we can not mention StellarTerm?

**Comment by irisli** [comment]
It's a request. Because you are using StellarTerm's name like it is an endorsement of your product.

**Comment by charnasol** [comment]
So if changed to say “you can use” as we just want to alert our users were they can trade.

**Comment by irisli** [comment]
I still prefer not. Thanks.

There is also another client: https://portal.stellarport.io/exchange/alphanum4/CHRC/GBRPTWEZTUKYM6VJXLHXBFI23M2GSY3TCVIQSZKFQLMOJXH7VPDGKBDP/native/XLM/Stellar

**Comment by charnasol** [comment]
We will remove. Is it staying on?

**Comment by irisli** [comment]
Thanks. For now, it is currently listed

**Comment by jonasess** [comment]
Hello . SSL has been changed https://charnatoken.top

**Comment by irisli** [comment]
It still doesn't redirect http://charnatoken.top

**Comment by jonasess** [comment]
Working on it to fix it

**Comment by jonasess** [comment]
Hello . i fixed it . you can check it now

**Pull request closed without merging**
